apiVersion: v1
kind: Service
metadata:
  labels:
    app: car-game
  name: car-game-service
  namespace: default
spec:
  ports:
    - nodePort: 32706
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: car-game
  type: NodePort
